# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bf.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x08\x62\x66.proto\"\xbe\x01\n\x10\x42\x66PipelineConfig\x12\x0f\n\x07p4_name\x18\x01 \x01(\t\x12\x16\n\x0e\x62\x66runtime_info\x18\x02 \x01(\x0c\x12+\n\x08profiles\x18\x03 \x03(\x0b\x32\x19.BfPipelineConfig.Profile\x1aT\n\x07Profile\x12\x14\n\x0cprofile_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\x0c\x12\x0e\n\x06\x62inary\x18\x03 \x01(\x0c\x12\x12\n\npipe_scope\x18\x04 \x03(\rb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BFPIPELINECONFIG_PROFILE = _descriptor.Descriptor(
  name='Profile',
  full_name='BfPipelineConfig.Profile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile_name', full_name='BfPipelineConfig.Profile.profile_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='context', full_name='BfPipelineConfig.Profile.context', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='binary', full_name='BfPipelineConfig.Profile.binary', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pipe_scope', full_name='BfPipelineConfig.Profile.pipe_scope', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=203,
)

_BFPIPELINECONFIG = _descriptor.Descriptor(
  name='BfPipelineConfig',
  full_name='BfPipelineConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='p4_name', full_name='BfPipelineConfig.p4_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bfruntime_info', full_name='BfPipelineConfig.bfruntime_info', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='profiles', full_name='BfPipelineConfig.profiles', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_BFPIPELINECONFIG_PROFILE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=203,
)

_BFPIPELINECONFIG_PROFILE.containing_type = _BFPIPELINECONFIG
_BFPIPELINECONFIG.fields_by_name['profiles'].message_type = _BFPIPELINECONFIG_PROFILE
DESCRIPTOR.message_types_by_name['BfPipelineConfig'] = _BFPIPELINECONFIG

BfPipelineConfig = _reflection.GeneratedProtocolMessageType('BfPipelineConfig', (_message.Message,), dict(

  Profile = _reflection.GeneratedProtocolMessageType('Profile', (_message.Message,), dict(
    DESCRIPTOR = _BFPIPELINECONFIG_PROFILE,
    __module__ = 'bf_pb2'
    # @@protoc_insertion_point(class_scope:BfPipelineConfig.Profile)
    ))
  ,
  DESCRIPTOR = _BFPIPELINECONFIG,
  __module__ = 'bf_pb2'
  # @@protoc_insertion_point(class_scope:BfPipelineConfig)
  ))
_sym_db.RegisterMessage(BfPipelineConfig)
_sym_db.RegisterMessage(BfPipelineConfig.Profile)


# @@protoc_insertion_point(module_scope)
